import Dashboard from "@/components/Dashboard/Dashboard";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";

const AdminDashBoard = () => {
  const router = useRouter();
  const { currentUser } = useSelector((state) => state.user);
  if (currentUser.length) {
    return (
      <>
        <Head>
          <title>Em-ship Admin Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Dashboard></Dashboard>
      </>
    );
  } else {
    router.push("/login");
  }
};

export default AdminDashBoard;
