import CategoryProducts from '@/components/Categories/CategoryCard/CategoryProducts/CategoryProducts';
import fetchCatProductData from '@/redux/thunk/products/fetchCatProduct';
import Head from 'next/head';

import { useRouter } from 'next/router';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';

const Products = () => {
    const dispatch = useDispatch();
    const router = useRouter()
    const { slug } = router.query
    useEffect(()=>{
        dispatch(fetchCatProductData(slug))
    },[dispatch,slug])
    
    return (
      <div>
        <Head>
          <title>Em-ship Category Product</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <CategoryProducts></CategoryProducts>
      </div>
    );
};

export default Products;
