import LoginForm from "@/components/LoginForm/LoginForm";
import Head from "next/head";
import { useSelector } from "react-redux";


const Login = () => {
    const { theme } = useSelector((state) => state.theme);
    return (
      <>
        <Head>
          <title>Em-ship Login</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div data-theme={theme ? "dark" : "light"} className="min-h-screen">
          <LoginForm></LoginForm>
        </div>
      </>
    );
};

export default Login;

Login.getLayout = function PageLayout(page) {
  return <>{page}</>;
};