import CustomerList from '@/components/CustomerList/CustomerList';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';

const Customer = () => {
    const router = useRouter();
    const { currentUser } = useSelector((state) => state.user);
    if (currentUser.length) {
        
        return (
          <>
            <Head>
              <title>Em-ship Customer List</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <CustomerList></CustomerList>
          </>
        );
    } else {
        router.push('/login')
    }
};

export default Customer;