import Categories from "@/components/Categories/Categories";
import Head from "next/head";
import React, { useEffect } from "react";


const Category = () => {

  return (
    <>
      <Head>
        <title>Em-ship Categories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Categories></Categories>
      </div>
    </>
  );
};

export default Category;
