import Head from "next/head";
import { Inter } from "next/font/google";

import { useDispatch, useSelector } from "react-redux";
import Stats from "@/components/HomePageSections/Stats/Stats";
import Banner from "@/components/HomePageSections/Banner/Banner";
import { useEffect } from "react";
import fetchProductData from "@/redux/thunk/products/fetchProducts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch=useDispatch()
  const { theme } = useSelector((state) => state.theme);
  const { products } = useSelector((state) => state.products);
  useEffect(() => {
    dispatch(fetchProductData())
  }, [dispatch]);
  console.log(products);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-5" data-theme={theme ? "dark" : "light"}>
        <Banner></Banner>
        <Stats></Stats>
      </div>
    </>
  );
}
