import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { toggleTheme } from "@/redux/actionCreators/themeToggle";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { theme } = useSelector((state) => state.theme);
  const dispatch = useDispatch();
  console.log(theme);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        ok
        <button
          onClick={() =>
            dispatch(toggleTheme())
          }
        >
          toggle
        </button>
      </div>
    </>
  );
}
