import Cart from '@/components/Cart/Cart';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { useSelector } from 'react-redux';

const MyCart = () => {
    const router = useRouter();
    const { currentUser } = useSelector((state) => state.user);
    if (currentUser.length) {
        
        return (
          <div className="min-h-[80vh]">
            <Head>
              <title>Em-ship My Cart</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Cart></Cart>
          </div>
        );
    } 
};

export default MyCart;